vich_uploader:
    db_driver: orm

    #       mappings:
    #       hotel:
    #       uri_prefix: /uploads/attachments # préfixe URI pour les téléchargements de fichiers d'hôtels
    #       upload_destination: '%kernel.project_dir%public/uploads/attachments' # répertoire de destination des téléchargements de fichiers d'hôtels
    #       namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
